### ISSUE TITLE
Remove the CPFP output of the Spend for deployments without Cosigning Servers

### ISSUE THREAD

**Issue by darosior** [revault/practical-revault#105]
They can always RBF which is:
- More cost efficient to them
- Less expensive in sats and logic (eg dust) to everyone

**Comment by darosior** [comment]
Related to #104

**Comment by JSwambo** [comment]
I think it makes more sense to have it as optional. It may be better in some cases to rely on CPFP if the burden of coordinating managers is already high.

**Comment by darosior** [comment]
Yes. From the meeting Yesterday i think we are rather leaning toward:
1. Make CPFP outputs optional
2. Implement an "RBF" feature (only possible for deployments without cosigning servers)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by darosior** [comment]
Closing in favour of #104 .
