### ISSUE TITLE
limit the number of stakeholders and managers to 20

### ISSUE THREAD

**Issue by darosior** [revault/practical-revault#110]
Limiting them to 20 would allow us to use a `multi()` descriptor for both the deposit and CPFP descriptor, greatly simplifying the implementation of `revaultd` until `bitcoind` supports Miniscript.

This also gives more reasonable bounds to the configuration possibilities and allows for better testing of most setups.

I think we can reasonably assume that the first deployments won't have more than 20 stks or mans. But can we?

**Comment by JSwambo** [comment]
I think we don't yet have a use case in mind where it'd be necessary to have > 20. Also I don't think anyone is doing that in the industry? Largest I've seen is nunchuck's 6/7 of 11. 

Even with a use case of always-online fully-automated managers, I can't see > 20 of them being used any time soon. 

I think it's ok.

**Comment by darosior** [comment]
This was also the sentiment during the meeting, let's do it.
