### ISSUE TITLE
Make coordinator act as a policy hinter

### ISSUE THREAD

**Issue by darosior** [revault/practical-revault#70]
The sync server could be configured with WTs policy, and could return a hint when the managers are pushing a transaction. It would of course be untrusted, but it's just a hint and could increase UX in an "everything is fine" scenario while not decreasing security in a rogue scenario (if it's just a boolean that is returned).

**Comment by kloaec** [comment]
Not convinced by the concept as such, but could be useful.
ACK as a tool or option thing.

**Comment by darosior** [comment]
I don't think this should be tracked here, closing.
