### ISSUE TITLE
Add a `doc` folder with the risk analysis paper's LaTex

### ISSUE THREAD

**Issue by darosior** [revault/practical-revault#77]
Also:
- Move the pdf there as well
- This is where we'd eventually add additional attack trees

**Comment by darosior** [comment]
Since we'd add more documentation this may as well be a subfolder of `doc`

**Comment by JSwambo** [comment]
So, under `practical-revault/doc/attack-trees/` we'll have `Risk Framework for Bitcoin Custody Operation with the Revault Protocol.pdf` and associated LaTex files, and additional attack tree work?

**Comment by darosior** [comment]
I was thinking of
```
doc/
    --> paper.pdf
    --> attack_trees.md
    --> README.md
```
