### ISSUE TITLE
Have all revocation signatures in a single message to the watchtower

### ISSUE THREAD

**Issue by darosior** [revault/practical-revault#85]
It makes sense as it's how we are using them in the daemon right now, and this way you can't be in a state where part of the revocation signatures were ACKed but not all

**Comment by JSwambo** [comment]
What about outsourced WTs that shouldn't be trusted with the Emergency?

**Comment by darosior** [comment]
Good point...

**Comment by darosior** [comment]
This was discussed on another medium with Jacob (and others). Outsourced watchtower are out of the scope for v0, but actually separating each transaction sig sharing allows us to more granularly allocate fee-bumping UTXOs: only do once we receive the signature for the UnvaultEmergency and Cancel transactions (wallet implicitly signals us the vault became active).
