### ISSUE TITLE
Do we need an insanely high feerate on the Emergency transaction?

### ISSUE THREAD

**Issue by darosior** [revault/practical-revault#86]
As discussed with Jacob, it seems better in practice.

**Comment by darosior** [comment]
Actually it's been so long i don't remember the conversation we had. I'm not sure an insanely high feerate is the right tradeoff as it comes at a large cost for the user and rules out small deposits (which may already be ruled out by WT reserve cost though).

@JSwambo do you remember why we decided this?

**Comment by JSwambo** [comment]
#106 fixes this
